---
abstract: 'Daemonise - a general daemoniser for anything...'
author:
  - 'Lenz Gschwendtner <norbu09@cpan.org>'
build_requires:
  Test::Deep: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.037, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Daemonise
requires:
  Basket::Calc: '0'
  Cache::KyotoTycoon: '0'
  Carp: '0'
  Config::Any: '0'
  Data::Dumper: '0'
  Data::Printer: '0'
  DateTime: '0'
  Digest::MD5: '0'
  File::Basename: '0'
  FindBin: '0'
  JSON: '0'
  LWP::UserAgent: '0'
  MIME::Base64: '0'
  Mouse: '0'
  Mouse::Role: '0'
  Net::AMQP::RabbitMQ: '0.300000'
  Net::Graphite: '0'
  POSIX: '0'
  Parallel::ForkManager: '0'
  Redis: '0'
  Riemann::Client: '0'
  Scalar::Util: '0'
  Storable: '0'
  Store::CouchDB: '0'
  Sys::Syslog: '0'
  Tie::Syslog: '0'
  True::Truth: '1.1'
  Try::Tiny: '0'
  WebService::PagerDuty: '0'
  experimental: '0'
  lib: '0'
  perl: '5.010'
resources:
  bugtracker: https://github.com/ideegeo/Daemonise/issues
  homepage: https://github.com/ideegeo/Daemonise/wiki
  repository: git://github.com/ideegeo/Daemonise.git
version: '1.95'
