---
abstract: 'Daemonise - a general daemoniser for anything...'
author:
  - 'Lenz Gschwendtner <norbu09@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Daemonise
requires:
  Cache::KyotoTycoon: 0
  Carp: 0
  Config::Any: 0
  Data::Dump: 0
  Data::Dumper: 0
  DateTime: 0
  Digest::MD5: 0
  FindBin: 0
  JSON: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
  Mouse: 0
  Mouse::Role: 0
  Net::Graphite: 0
  Net::RabbitMQ: 0
  POSIX: 0
  Redis: 0
  Riemann::Client: 0
  Scalar::Util: 0
  Storable: 0
  Store::CouchDB: 0
  Tie::Syslog: 0
  Try::Tiny: 0
  Unix::Syslog: 0
  WebService::PagerDuty: 0
  experimental: 0
  feature: 0
  lib: 0
  perl: 5.010
resources:
  bugtracker: https://github.com/ideegeo/Daemonise/issues
  homepage: https://github.com/ideegeo/Daemonise/wiki
  repository: git://github.com/ideegeo/Daemonise.git
version: 1.56
