---
abstract: 'a general daemoniser for anything...'
author:
  - 'Lenz Gschwendtner <norbu09@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Daemonise
no_index:
  directory:
    - inc
    - t
requires:
  Config::Any: 0
  Moose: 0
  Unix::Syslog: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.2
